# training Configuration parameters
NUM_LINKS = 4
INPUT_SIZE = NUM_LINKS + 2  # Joint angles + 2D point
HIDDEN_SIZE = 256
OUTPUT_SIZE = NUM_LINKS
NUM_LAYERS = 5

NUM_EPOCHS = 3000
LEARNING_RATE = 0.0015
BATCH_SIZE = 256